### listing resource
GET http://localhost:3000/v1/employees

### getting resource
GET http://localhost:3000/v1/employees/1

### creating resource
POST http://localhost:3000/v1/employees
Content-Type: application/json

{
    "name": "Bambang",
    "departement": "hrd",
    "salary": 10000000,
    "is_manager": false
}

### updating resource
PUT http://localhost:3000/v1/employees/2
Content-Type: 'application/json'

{
    "name": "Bambang",
    "departement": "HRD",
    "salary": 10000000,
    "is_manager": true
}

### deleting resource
DELETE http://localhost:3000/v1/employees/3


